version: '3'
services:
    db:
        image: postgres:12.8
        hostname: 'blockscout-db'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ChangeMe1!
            POSTGRES_USER: postgres
    blockscout:
        image: surfingnerd/blockscout:v0.9-411
        depends_on:
            - "db"
        hostname: 'blockscout-app'
        ports:
            - "4444:4000"
        tty: true
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: https://rpc-testnet.lamina1.com/ext/bc/C/rpc
            # ETHEREUM_JSONRPC_TRACE_URL: http://172.17.0.1:9652
            #ETHEREUM_JSONRPC_WS_URL: ws://rpc-testnet.lamina1.com/ext/bc/C/ws
            #ETHEREUM_JSONRPC_VARIANT: parity
            DATABASE_URL: postgresql://postgres:ChangeMe1!@blockscout-db:5432/explorer?ssl=false

networks:
    default:
        name: devnpmnet
        external: true
